### PR TITLE
Minor code cleanups, spelling, remove unused code.

### PR DESCRIPTION
**Pull request by jasonschroeder**
Hi! Your project caught my eye and I hope I can help out!
Cheers

### CODE REVIEW

**Comment by jo3co** [comment]
Hello buddy! Im all alone in this project and If you would like to contribuite I sure could use some help! Do you have any dji drone or osmo? Cheers!

**Comment by jasonschroeder** [comment]
DJI Phantom4 :smile:

**Comment by jo3co** [comment]
That is great buddy! I wont merge your pull yet because im travelling. Be back in a few days. Have some milestones we need to acheive before releasing a beta. If you could test the current code in the simulator and see if its working in the ph4 that would be great! Cheers!

**Comment by dbaldwin** [comment]
@jasonschroeder welcome to the project! We're excited to have you on board and @jo3co has taken initiative with a DronePan Android rewrite. I just just tested your branch with my P4 sim and everything works the same as before so I'll go ahead and merge. FYI please feel free to join our gitter chat: https://gitter.im/dbaldwin/DronePan and Facebook group: https://www.facebook.com/groups/dronepan

**Pull request merged**
